### ISSUE TITLE
Delete List Item

### ISSUE THREAD

**Issue by felix-horn** [felix-horn/capstone-project#10]
## Value Statement
As a **user**, 
I need **to delete list items**, 
so that **I don't have list items on my list, which I won't buy again**. 

## Description (Text, Scribble, Wireframe, Design)

![grafik](https://user-images.githubusercontent.com/71647387/99442039-0b927180-2919-11eb-8a9b-757bb848124e.png)

(Red circle indicates user interaction / touch.)

## Acceptance Criteria
- [x] By clicking the [x] button, the corresponding list item (including its checkbox) is removed from its list.
- [x] This is the same for checked and unchecked list items.
- [x] Everything below the deleted list item shifts up to fill the empty line.

## Tasks
- [x] Create feature branch.
- [x] Create [x] button component in Styleguidist.
- [x] Write unit tests.
- [x] Write intergration tests.
- [x] Add logic to app.
- [x] Add missing styles.

## Complexity
small
