### ISSUE TITLE
Show Checkbox while Adding New List Item

### ISSUE THREAD

**Issue by felix-horn** [felix-horn/capstone-project#11]
## Value Statement
As a **user**, 
I need **to add items to the list**, 
so that **I can do my grocery shopping**. 

## Description (Text, Scribble, Wireframe, Design)

![grafik](https://user-images.githubusercontent.com/71647387/99242360-5d46d900-27ff-11eb-9d65-f62fc9fe4614.png)

## Acceptance Criteria
- [x] By clicking on the button [Listeneintrag], a new checkbox is created and the title of the list item can be entered.
- [x] The new checkbox is not checked.
- [x] The button [Listeneintrag] is dispayed in the next line. (img 2)
- [x] By hitting enter or clicking outside the input field, the list item title is saved.
- [x] It is possible to save an empty input.
- [x] In this case the space next to the checkbox is empty. (img 4)

## Tasks
- [x] Create feature branch.
- [x] Create [+ Listeneintrag] button component in Styleguidist.
- [x] Write component tests.
- [x] Create <[ ] List Item> component in Styleguidist.
- [x] Create <[ ] input field> component in Styleguidist.
- [x] Add components to app.
- [x] Add missing styles.

## Complexity
medium
