### ISSUE TITLE
Add List Item

### ISSUE THREAD

**Issue by felix-horn** [felix-horn/capstone-project#4]
## Value Statement
As a **user**, 
I need **to add items to the list**, 
so that **I can do my grocery shopping**. 

## Description (Text, Scribble, Wireframe, Design)

![grafik](https://user-images.githubusercontent.com/71647387/99441849-c66e3f80-2918-11eb-9286-07bc20689b88.png)

(Red circle indicates user interaction / touch.)

## Acceptance Criteria
- [x] The title of a new list item can be entered into the input field.
- [x] By hitting enter, the list item title is saved.
- [x] The checkbox of the new list item is not checked.
- [x] It is possible to save an empty input.
- [x] In this case the space next to the checkbox is empty. (img 4)

## Tasks
- [x] Create feature branch.
- [x] Create <InputField> UI-element in Styleguidist.
- [x] Write unit test.
- [x] Create <ListItem> UI-element in Styleguidist.
- [x] Write unit test.
- [x] Create <List> component in Styleguidist.
- [x] Write unit test.
- [x] Add components to app.
- [x] Add missing styles.

## Complexity
small
