### ISSUE TITLE
Check and Uncheck List Items

### ISSUE THREAD

**Issue by felix-horn** [felix-horn/capstone-project#5]
## Value Statement
As a **user**, 
I need **to toggle the list items' checkmark**, 
so that **I know, which items I do not have to buy when shopping or add them bag to the list**. 

## Description (Text, Scribble, Wireframe, Design)

![grafik](https://user-images.githubusercontent.com/71647387/99441956-edc50c80-2918-11eb-8ea1-aa519c8d557b.png)

(Red circle indicates user interaction / touch.)

## Acceptance Criteria
- [x] When an **uncheckd** box is clicked, the box shows a checkmark. 
- [x] The corresponding list item (including the checkbox) is removed from the list of unchecked items.
- [x] The list item (including its checked box) is added to the list of checked items.
- [x] The new item is added to the top of the list of checked items. 
- [x] When an **checked** box is clicked, it gets unchecked. 
- [x] The corresponding list item (including the checkbox) is removed from the list of checked items.
- [x] The list item (including its unchecked box) is added to the list of unchecked items.
- [x] The new item is added to the bottom of the list of unchecked items. 

## Tasks
- [x] Create feature branch.
- [x] Write unit tests.
- [x] Write integration tests.
- [x] Add logic to app.
- [x] Add missing styles.

## Complexity
small
