### ISSUE TITLE
Uncheck List Item

### ISSUE THREAD

**Issue by felix-horn** [felix-horn/capstone-project#6]
## Value Statement
As a **user**, 
I need **to uncheck list items**, 
so that **I can easily add them to my grocery list again**. 

## Description (Text, Scribble, Wireframe, Design)

<img width="605" alt="grafik" src="https://user-images.githubusercontent.com/71647387/99192930-f7623f00-2775-11eb-804e-3c2e650208cc.png">

## Acceptance Criteria
- [ ] When an checked box is clicked, the box shows is unchecked. 
- [ ] The corresponding list item (including the checkbox) is removed from the list of checked items.
- [ ] The list item (including its unchecked box) is added to the list of unchecked items.
- [ ] The new item is added to the top of the list of unchecked items. 

## Tasks
- [ ] Create feature branch.
- [ ] Write component tests.
- [ ] Add logic to app.
- [ ] Add missing styles.

## Complexity
small
