### ISSUE TITLE
Delete List Item (Edit)

### ISSUE THREAD

**Issue by felix-horn** [felix-horn/capstone-project#7]
## Value Statement
As a **user**, 
I need **to delete list items**, 
so that **I don't have list items on my list, which I won't buy again**. 

## Description (Text, Scribble, Wireframe, Design)

<img width="1271" alt="grafik" src="https://user-images.githubusercontent.com/71647387/99193190-a6534a80-2777-11eb-85e1-6d95bcdedc24.png">

## Acceptance Criteria
- [x] When a list item is eddited, an [x] button appears to the right of the item title. 
- [x] This is the same for checked and unchecked list items.
- [x] By clicking the [x] button, the corresponding list item (including its checkbox) is removed from its list.
- [x] Everything below the deleted list item shifts up to fill the empty line.
- [x] The [x] button already appears the first time the list item is created. (img 5)

## Tasks
- [x] Create feature branch.
- [x] Create [x] button component in Styleguidist.
- [x] Write component tests.
- [x] Add logic to app.
- [x] Add missing styles.

## Complexity
small
