### ISSUE TITLE
Edit List Item

### ISSUE THREAD

**Issue by felix-horn** [felix-horn/capstone-project#8]
## Value Statement
As a **user**, 
I need **to edit list items**, 
so that **I can change correct spelling mistakes or paraphrase them**. 

## Description (Text, Scribble, Wireframe, Design)

<img width="493" alt="grafik" src="https://user-images.githubusercontent.com/71647387/99193341-a0119e00-2778-11eb-9b79-483776d72f50.png">

## Acceptance Criteria
- [x] By clicking on a list item, it can be edited.
- [x] This is the same for checked and unchecked list items.
- [x] By hitting enter or clicking outside the input field, the list item title is saved.
- [x] Again, it is possible to save an empty input.

## Tasks
- [x] Create feature branch.
- [x] Write component tests.
- [x] Add logic to app.

## Complexity
low
